#!/usr/bin/env python3
"""Generate pkg/sqlfn/pg_catalog_gen.go from Postgres 14.5's catalog data files.

Usage: gen.py <dir holding pg_proc.dat pg_cast.dat pg_type.dat kwlist.h system_functions.sql Default> > pkg/sqlfn/pg_catalog_gen.go

The data files are those of REL_14_5 (src/include/catalog, src/include/parser/kwlist.h, and
src/backend/catalog/system_functions.sql, which declares the argument defaults pg_proc.dat lacks,
and src/timezone/tznames/Default, the timezone_abbreviations set a server starts with). The functions emitted are those the
Postgres catalogue implements, listed in NAMES; every overload of each is emitted, so overload
resolution sees what Postgres sees.
"""
import json, re, sys

def q(s):
    return json.dumps(s)

NAMES = sys.stdin.read().split()

def blocks(s):
    """Top-level { ... } entries, braces inside quoted values left alone."""
    out, depth, start, inq, i = [], 0, 0, False, 0
    while i < len(s):
        c = s[i]
        if inq:
            if c == '\\':
                i += 1
            elif c == "'":
                inq = False
        elif c == "'":
            inq = True
        elif c == '{':
            if depth == 0:
                start = i + 1
            depth += 1
        elif c == '}':
            depth -= 1
            if depth == 0:
                out.append(s[start:i])
        i += 1
    return out

def entries(path):
    s = open(path).read()
    s = re.sub(r'#[^\n]*', '', s)
    out = []
    for block in blocks(s):
        d = {}
        for k, v in re.findall(r"(\w+)\s*=>\s*'((?:[^'\\]|\\.)*)'", block):
            d[k] = v.replace("\\'", "'")
        if d:
            out.append(d)
    return out

d = sys.argv[1]
types = entries(d + '/pg_type.dat')
casts = entries(d + '/pg_cast.dat')
procs = entries(d + '/pg_proc.dat')

def split_top(s):
    """s split at its top-level commas."""
    out, depth, cur, inq = [], 0, '', False
    for c in s:
        if c == "'":
            inq = not inq
        elif not inq and c == '(':
            depth += 1
        elif not inq and c == ')':
            depth -= 1
        if c == ',' and depth == 0 and not inq:
            out.append(cur)
            cur = ''
        else:
            cur += c
    out.append(cur)
    return out

# defaults[name][nargs] = the default literals of the trailing arguments, as system_functions.sql
# declares them.
defaults = {}
sf = re.sub(r'--[^\n]*', '', open(d + '/system_functions.sql').read())
for m in re.finditer(r'CREATE OR REPLACE FUNCTION\s+(\w+)\s*\((.*?)\)\s*RETURNS', sf, re.S):
    params = split_top(m.group(2))
    lits = []
    for prm in params:
        dm = re.search(r"DEFAULT\s+('(?:[^']|'')*'|[\w.+-]+)", prm)
        if dm:
            v = dm.group(1)
            if v.startswith("'"):
                v = v[1:-1].replace("''", "'")
            lits.append(v)
    if lits:
        defaults.setdefault(m.group(1), {})[len(params)] = lits

tinfo = {}
for t in types:
    name = t['typname']
    tinfo[name] = (t.get('typcategory', 'U'), t.get('typispreferred', 'f') == 't')
    if 'array_type_oid' in t:
        tinfo['_' + name] = ('A', False)

out = ['// Code generated by internal/tools/pgcatalog from Postgres 14.5\'s catalog data. DO NOT EDIT.', '',
       'package sqlfn', '',
       '// pgTypeInfo is each type\'s category and whether it is its category\'s preferred type (pg_type).',
       'var pgTypeInfo = map[string]pgTypeCategory{']
for name in sorted(tinfo):
    c, p = tinfo[name]
    out.append('\t%s: {%s, %s},' % (q(name), q(c), 'true' if p else 'false'))
out.append('}')
out.append('')
out.append('// pgImplicitCasts are the casts Postgres applies implicitly (pg_cast, castcontext i).')
out.append('var pgImplicitCasts = map[[2]string]bool{')
for c in casts:
    if c.get('castcontext') == 'i':
        out.append('\t{%s, %s}: true,' % (q(c['castsource']), q(c['casttarget'])))
out.append('}')
out.append('')
out.append('// pgBinaryCasts are the casts needing no conversion (pg_cast, castmethod b).')
out.append('var pgBinaryCasts = map[[2]string]bool{')
for c in casts:
    if c.get('castmethod') == 'b':
        out.append('\t{%s, %s}: true,' % (q(c['castsource']), q(c['casttarget'])))
out.append('}')
out.append('')
out.append('// pgProcs are every overload of each function the Postgres catalogue implements (pg_proc).')
out.append('var pgProcs = map[string][]pgProc{')
for n in NAMES:
    rows = [p for p in procs if p.get('proname') == n]
    if not rows:
        sys.exit('no pg_proc entry for ' + n)
    out.append('\t%s: {' % q(n))
    for p in rows:
        args = p.get('proargtypes', '').split()
        allargs = p.get('proallargtypes')
        modes = p.get('proargmodes')
        variadic = p.get('provariadic', '')
        cols = []
        if allargs and modes:
            names = p.get('proargnames', '{}').strip('{}').split(',')
            for t, m, nm in zip(allargs.strip('{}').split(','), modes.strip('{}').split(','), names):
                if m in ('o', 't'):
                    cols.append(nm)
        defs = defaults.get(n, {}).get(len(args), [])
        out.append('\t\t{src: %s, args: []string{%s}, ret: %s, retset: %s, variadic: %s, strict: %s, outs: []string{%s}, defaults: []string{%s}},' % (
            q(p.get('prosrc', '')), ', '.join(q(a) for a in args), q(p['prorettype']),
            'true' if p.get('proretset') == 't' else 'false', q(variadic),
            'false' if p.get('proisstrict') == 'f' else 'true', ', '.join(q(c) for c in cols),
            ', '.join(q(x) for x in defs)))
    out.append('\t},')
out.append('}')
out.append('')
out.append('// pgQuotedKeywords are the SQL keywords quote_ident quotes: all but the unreserved (kwlist.h).')
out.append('var pgQuotedKeywords = map[string]bool{')
for kw, cat in re.findall(r'PG_KEYWORD\("(\w+)", \w+, (\w+), \w+\)', open(d + '/kwlist.h').read()):
    if cat != 'UNRESERVED_KEYWORD':
        out.append('\t%s: true,' % q(kw))
out.append('}')
out.append('')
out.append('// pgTZAbbrevs are the time zone abbreviations of the Default set (tznames/Default), sorted as')
out.append('// datebsearch reads them: a fixed offset east of UTC, DST-flagged or not, or a zone whose offset')
out.append('// at the time decides.')
out.append('var pgTZAbbrevs = []pgTZAbbrev{')
abbrevs = []
for line in open(d + '/Default'):
    line = line.split('#', 1)[0].split()
    if not line:
        continue
    if line[0].startswith('@'):
        sys.exit('unexpected directive in Default: ' + line[0])
    abbr = line[0].lower()
    if line[1].lstrip('-').isdigit():
        abbrevs.append((abbr, int(line[1]), len(line) > 2 and line[2] == 'D', ''))
    else:
        abbrevs.append((abbr, 0, False, line[1]))
abbrevs.sort(key=lambda a: a[0].encode())
for a, off, dst, zone in abbrevs:
    out.append('\t{%s, %d, %s, %s},' % (q(a), off, 'true' if dst else 'false', q(zone)))
out.append('}')
print('\n'.join(out))
