#!/usr/bin/env python3
"""Generate pkg/sqlfn/pg_zonenames_gen.go: the time zone names stackql's Postgres image accepts.

Usage: docker run --rm postgres:14.5-bullseye find /usr/share/zoneinfo -type f -o -type l | zones.py > pkg/sqlfn/pg_zonenames_gen.go

The image's Postgres reads the system tzdata (Debian builds it --with-system-tzdata), matching a name
without regard to case. Names under posix/ are the same zones; right/ ones count leap seconds and
the tables (zone.tab and the like) are not zones.
"""
import sys

root = '/usr/share/zoneinfo/'
names = {}
for line in sys.stdin:
    p = line.strip()
    if not p.startswith(root):
        continue
    name = p[len(root):]
    if name.startswith('right/') or name.endswith('.tab') or name.endswith('.zi') or '.' in name.split('/')[-1] \
            or name in ('leapseconds', 'leap-seconds.list', 'SECURITY', 'localtime'):
        continue
    canon = name[len('posix/'):] if name.startswith('posix/') else name
    names[name.lower()] = canon
out = ['// Code generated by internal/tools/pgcatalog/zones.py from postgres:14.5-bullseye. DO NOT EDIT.', '',
       'package sqlfn', '',
       '// pgZoneNames maps each time zone name the image accepts, lowercased, to the zone it names.',
       'var pgZoneNames = map[string]string{']
for k in sorted(names):
    out.append('\t"%s": "%s",' % (k, names[k]))
out.append('}')
print('\n'.join(out))
